### PR TITLE
Refactor using a buffer for reading and a buffer for writing

### PR DESCRIPTION
**Pull request by Kryptos-FR**
Following the [discussion](https://www.reddit.com/r/rust/comments/p6ziiz/i_just_published_my_first_crate/) on reddit, this is my attempt at using buffers.

Note that I am also fairly new to rust, so it might not be the best implementation.

### CODE REVIEW

**Comment by Noratrieb** [comment]
Thank you for your contribution, I'll look into it later!

**Comment by Kryptos-FR** [comment]
Take your time, there is no need to hurry.

I took it as a way to exercise myself with rust after reading the conversation on reddit 😀

**Comment by Noratrieb** [comment]
I used `time` to test both versions, and your fix used *significantly* less RAM than the original version (3k vs 172k), but it's also about 5 times slower, which is not very good. I'll try to optimize your version some more and I'm sure I can get the time down by quite a bit.

**Comment by Noratrieb** [comment]
I've tried some stuff but nothing has really worked so far, it's still too slow. I'll probably try another day but as long as it's so slow, I can't merge it, even if the current memory footprint is too high. If you want to try, you can try to make it faster of course.

**Comment by Kryptos-FR** [comment]
It is expected to be a bit slower but my own testing with huge json files (100 MB, 1 GB) only showed about 1.5x to 2x slower. Not sure how you get 5x.

It could be system-dependent. Mine is:
```
Intel Core i5-6600K @ 3.50 GHz
16 GB RAM
Samsung SSD 840 Pro Series (40 GB free)
```

**Comment by Noratrieb** [comment]
I am testing in on my
```
AMD Ryzen 3950X @ 3.50 GHz
32 GB RAM
Samsung NVME SSD 970 EVO (i think) 1TB
```
I was testing in in WSL but forgot that WSL in the windows filesystem is very slow for IO, so I copied everything into the WSL fs and ran it again using my ~60GB file.

Buffered:
```
        Command being timed: "target/release/jsonformat massive.json -o massivef.json"
        User time (seconds): 1.18
        System time (seconds): 0.04
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.23
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 2412
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 109
        Voluntary context switches: 1
        Involuntary context switches: 1
        Swaps: 0
        File system inputs: 0
        File system outputs: 218280
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```
Original:
```
        Command being timed: "target/release/jsonformat massive.json -o massivef.json"
        User time (seconds): 0.27
        System time (seconds): 0.13
        Percent of CPU this job got: 100%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.40
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 172152
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 1175
        Voluntary context switches: 1
        Involuntary context switches: 0
        Swaps: 0
        File system inputs: 0
        File system outputs: 218280
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

It got better but it is still significantly slower.
I also ran the benchmarks (which don't do any IO and only work in in-memory strings) and the results were the following:

Buffered: `[1.4163 s 1.4205 s 1.4259 s]`  
Original: `[310.37 ms 310.83 ms 311.31 ms]`


While I can't be sure what is exactly causing this since I haven't been able to run a flamegraph on it, I think it probably comes from the char pushes into the `BufWriter`, there seems to be a lot more overhead there compared to `String::push`, which just pushes the char as a byte if the utf8 length is 0. But if you can create a flamegraph, that would be very useful.

**Comment by Kryptos-FR** [comment]
There are a couple issues for sure. One was with using the `utf8-chars` crate. Turns out we don't need it since all the characters we ever compare with are single byte.

Another issue is that despite the use of buffers, I think all writes are blocking the reads. Ideally, it should use some kind of producer-consumer pattern and push characters (or rather bytes now) into a queue and another thread would read from that queue and write to the output. I know how to do that in c# but I'm not familiar with the rust APIs.

I have added one commit to get rid of `utf8-chars` first, which already gives marginally better results.

**Comment by Kryptos-FR** [comment]
I did some manual testing again. And what I found out is that the slowdown is much less than 2x especially for bigger files.

One mistake I did previously was to just rebuild (using `cargo build --release`) when switching branches or commit. Turns out that the incremental build might miss some optimization that way (my assumption). However I get much more reliable results when doing a `cargo clean` before each build.

25 MB 
| commit or branch | time   | ratio |
|------------------|--------|-------|
| *master*           | *0.184s* | *1.0*   |
| f8c49ca6         | 0.406s | 2.21  |
| 8832d617         | 0.339s | 1.84  |
| 9652a464         | 0.331s | 1.80  |

180 MB
| commit or branch | time   | ratio |
|------------------|--------|-------|
| *master*           | *2.441s* | *1.0*   |
| f8c49ca6         | 3.263s | 1.34  |
| 8832d617         | 2.680s | 1.10  |
| 9652a464         | 2.590s | 1.06  |

1 GB
| commit or branch | time    | ratio |
|------------------|---------|-------|
| *master*           | *14.632s* | *1.0*   |
| f8c49ca6         | 19.069s | 1.30  |
| 8832d617         | 15.757s | 1.08  |
| 9652a464         | 15.140s | 1.03  |

10 GB
| commit or branch | time      | ratio |
|------------------|-----------|-------|
| *master*           | *crash*  | -   |
| f8c49ca6         | 3m10.149s | -  |
| 8832d617         | 3m13.556s | -  |
| 9652a464         | 3m8.984s  | -  |

Unbuffered version crashed with error: `memory allocation of 40992095520 bytes failed` .

To me those are acceptable results, and the small price paid for smaller files is worth it when you consider it also allows to deal with much bigger files.

**Comment by Noratrieb** [comment]
I'm sorry that I didn't answer earlier, but these results look pretty good. Waiting a hundred milliseconds longer on small files is not really a problem, and waiting a few seconds longer on really large files is also not an issue. Crashing and a huge memory usage is an issue though, so this change is really good.

I'll take a last look at it later today and then I'll probably merge it!

**Comment by Kryptos-FR** [comment]
@Nilstrieb thanks. And don't be sorry for not replying quickly, we all have other matters to attend to 😉

**Pull request merged**
